# cluster.yaml - cluster configuration for my Snakefile.
__default__:
  time: '2:00:00'
  cores: 2

iterative_search:
  time: '18:00:00'
  cores: 20

taxid_parse:
  time: '16:00:00'
  cores: 2

phydms:
  time: '8:00:00'
  cores: 20

realignment:
  time: '10:00:00'
  cores: 20
