# Folder where input data is stored
input_dir: "/groups/doudna/projects/daniel_projects/prywes_n/input_data/all_form_2"

threads: 20

# File directory where files will be stored in
run: "/groups/doudna/projects/daniel_projects/prywes_n/all_form_2"

min_ident: ['0.0', '0.60']
site_offset: 2

reference_seq:
  'all_form_2': 'WP_011390153.1'

#reference_fasta:
#  'all_form_2': "fasta/WP_011390153.1.fna"

rax_path: "raxmlHPC-PTHREADS-SSE3"

# Column names as displayed in the dms table
position_col: "Site"
enrichment_col: "5percent_CO2_20uM_IPTG"
aminoacid_col: "AminoAcid"
